///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class User {
/*
{
  "id": "hello",
  "email": "seth@gmail"
} 
*/

  String id;
  String email;

  User({
    this.id,
    this.email,
  });
  User.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    email = json["email"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["email"] = email;
    return data;
  }
}
